name: Python

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup UV
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install all dependencies
        run: uv sync --all-extras

      - name: Check code (ruff)
        run: uv run ruff check

      - name: Format code (ruff)
        run: uv run ruff format

      - name: Check typing (mypy)
        run: uv run mypy

      - name: Run unit-tests and generate coverage in console
        run: uv run pytest --verbose --cov=src tests
